let mapleader = "\<space>"

"=== Appearance ==="
syntax enable
set number relativenumber
set splitbelow splitright                       " Split window below/right
set scrolloff=5                                 " At least left 5 line
set wildmenu                                    " Enable auto completion menu after pressing TAB
set completeopt+=menuone                        " Show menu even if there is only one item
set completeopt-=preview                        " Disable the preview window
set ruler                                       " Show the cursor's position
set nowrap

"=== Tab/Indent ==="
set tabstop=4       " number of visual space per TAB
set softtabstop=4   " number of spaces in tab when editing
set shiftwidth=4    " number of spaces to use for autoindent
set expandtab       " expand tab to spaces so that tabs are spaces
set smarttab
set autoindent

"=== Search/Highlight ==="
set ignorecase smartcase
set incsearch
set hlsearch

"=== Variables ==="
let g:loaded_netrwPlugin = 1
let g:loaded_2html_plugin =1


"=== Other ==="
set nocompatible
filetype plugin indent on
set history=200
set noswapfile
set nobackup
set modelines=0
set nomodeline
set autoread
set confirm
set clipboard^=unnamed,unnamedplus
set encoding=utf-8
set spelllang=en,cjk

"=== General Keymap ==="
nnoremap <silent> <Space>sv :source $MYVIMRC<CR>

" Disable arrow keys
nnoremap <up> :echoerr "Don't use arrow keys, use H, J, K, L instead!"<CR>
nnoremap <down> :echoerr "Don't use arrow keys, use H, J, K, L instead!"<CR>
nnoremap <right> :echoerr "Don't use arrow keys, use H, J, K, L instead!"<CR>
nnoremap <left> :echoerr "Don't use arrow keys, use H, J, K, L instead!"<CR>

" Do thing without registers
nnoremap c "_c
nnoremap C "_C
nnoremap cc "_cc
nnoremap x "_x
nnoremap <leader>p "0p
nnoremap <leader>P "0P
nnoremap <leader>c "_c
nnoremap <leader>C "_C
nnoremap <leader>d "_d
nnoremap <leader>D "_D
vnoremap <leader>p "0p
vnoremap <leader>c "_c
vnoremap <leader>C "_C
vnoremap <leader>d "_d
vnoremap <leader>D "_D

" Quicker window movement
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l

" Resize split windows using arrow keys by pressing:
" CTRL+UP, CTRL+DOWN, CTRL+LEFT, or CTRL+RIGHT.
noremap <c-up> <c-w>+
noremap <c-down> <c-w>-
noremap <c-left> <c-w>>
noremap <c-right> <c-w><

"=== Autocmd ==="
" Delete all space at the end of line while saving
autocmd BufWritePre * :%s/\s\+$//e
